services:
  - type: web
    name: jobfit-server
    env: node
    branch: main
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: node app.js
    envVars:
      - key: AIzaSyCDJN2xMoFIHBMiaMUmMENc4hTCxTLYJY0
        sync: false
      - key: mongodb+srv://kourinderjeet386:Mithe%40123@inderjeetcluster.wc4av4q.mongodb.net/?retryWrites=true&w=majority&appName=Inderjeetcluster
        sync: false
